<?php

declare(strict_types=1);

namespace Pollora\AiVisibility\Generator;

use Pollora\AiVisibility\Plugin;
use Pollora\AiVisibility\Support\Filters;

/**
 * Generates the /.well-known/ai.txt file.
 * Declares AI usage permissions and preferences.
 */
final class AiTxtGenerator
{
    public function generate(): string
    {
        $settings = Plugin::settings();
        $siteUrl = home_url('/');
        $lines = [];

        $lines[] = '# AI Usage Permissions';
        $lines[] = '# Generated by AI Visibility for WordPress';
        $lines[] = '';
        $lines[] = 'Name: ' . get_bloginfo('name');
        $lines[] = 'Site: ' . $siteUrl;

        $description = trim($settings['site_description']) ?: get_bloginfo('description');
        if ($description !== '') {
            $lines[] = 'Description: ' . str_replace("\n", ' ', $description);
        }

        $lines[] = '';
        $lines[] = '# Policies';

        // Derive policies from crawler settings
        $allowed = $settings['crawlers_allow'];
        $blocked = $settings['crawlers_block'];

        if ($allowed !== []) {
            $lines[] = 'Policy: allow-ai-search';
        }
        if ($blocked !== []) {
            $lines[] = 'Policy: disallow-ai-training';
        }

        $lines[] = '';
        $lines[] = '# Discovery Files';
        $lines[] = 'LLMS-TXT: ' . $siteUrl . 'llms.txt';
        $lines[] = 'LLMS-Full-TXT: ' . $siteUrl . 'llms-full.txt';
        $lines[] = 'Identity: ' . $siteUrl . '.well-known/identity.json';
        $lines[] = 'Sitemap: ' . $siteUrl . 'sitemap.xml';

        $email = $settings['identity_email'];
        if ($email !== '') {
            $lines[] = '';
            $lines[] = '# Contact';
            $lines[] = 'Contact: ' . $email;
        }

        return Filters::string('ai_visibility_ai_txt', implode("\n", $lines) . "\n");
    }
}
